properties=
android.useAndroidX=true
#android.enableJetifier=true
android.enableJetifier=false
org.gradle.caching = true
org.gradle.parallel = true
org.gradle.configureondemand = true
org.gradle.vfs.watch = true
# lint needs more memory
org.gradle.jvmargs=-Xmx4g -XX:MaxMetaspaceSize=512m

# Added by AGP 9.0; these are the "safe" settings,
# proguard.cf should be tripple-checked before removing these.
android.r8.strictFullModeForKeepRules=false
android.r8.optimizedResourceShrinking=false
#android.aapt2FromMavenOverride=/home/xvsu/idea-IU-253.32098.37/android-sdk-tools-static-aarch64/build-tools/aapt2
