properties=
android.useAndroidX=true
#android.enableJetifier=true
android.enableJetifier=false
org.gradle.caching = true
org.gradle.parallel = true
org.gradle.configureondemand = true
org.gradle.vfs.watch = true
# lint needs more memory
org.gradle.jvmargs=-Xmx4g -XX:MaxMetaspaceSize=512m

# Added by AGP 9.0; these are the "safe" settings,
# proguard.cf should be tripple-checked before removing these.
android.r8.strictFullModeForKeepRules=false
android.r8.optimizedResourceShrinking=false
#android.aapt2FromMavenOverride=/home/xvsu/idea-IU-253.32098.37/android-sdk-tools-static-aarch64/build-tools/aapt2
# Use local JDK for toolchains and avoid downloading
#org.gradle.java.installations.paths=/opt/jdk
org.gradle.java.installations.auto-download=false

# Use proxy for dependency resolution
systemProp.http.proxyHost=172.25.0.1
systemProp.http.proxyPort=7890
systemProp.https.proxyHost=172.25.0.1
systemProp.https.proxyPort=7890
systemProp.http.nonProxyHosts=localhost|127.0.0.1
